=== dont-code/monorepo/libs/core/packages/core/src/assets/schemas/v1/repository-schema.json
{
  "$id": "https://dont-code.net/v1/repository-schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "JSON Schema v1 for plugin repository definition",
  "type": "object",
  "required": ["name", "plugins"],
  "properties": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "webSocketUrl": {
      "type": "string"
    },
    "storeApiUrl": {
      "type": "string"
    },
    "projectApiUrl": {
      "type": "string"
    },
    "documentApiUrl": {
      "type": "string"
    },
  
    "plugins": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/plugin"
      }
    }
  },
  "$defs": {
    "plugin": {
      "type": "object",
      "required": ["id", "version"],
      "properties": {
        "id": {
          "type": "string"
        },
        "display-name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "info": {
            "$refs": "#/$defs/plugin-info"
        },
        "config": {
          "$refs": "#/$defs/plugin-config"
        }
      }
    },
    "plugin-info": {
      "type": "object",
      "properties": {
        "exposed-module": {
          "type": "string"
        },
        "remote-entry": {
          "type": "uri"
        }
      }
    },
    "plugin-config": {
      "type": "object",
      "properties": {
        "definition-updates": {
          "$refs": "definition-update"
        }
      }
    },
    "definition-update": {
      "type": "object",
      "properties": {
        "location": {
          "$ref": "#/$defs/change-location"
        },
        "update": {
          "$ref": "#/$defs/additem"
        }
      }
    },
    "change-location": {
      "type": "object",
      "required": ["parent", "id"],
      "properties": {
        "parent": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "before": {
          "type": "string"
        },
        "after": {
          "type": "string"
        }
      },
      "additionalProperties": true
    },
    "additem": {
      "type": "object",
      "properties": {},
      "additionalProperties": true
    }
  }
}

=== dont-code/monorepo/apps/preview-ui/apps/preview-ui/src/assets/repositories/next.json
{
  "$schema": "https://dont-code.net/schemas/v1/repository-schema.json",
  "name": "Next Repository",
  "description": "Repository provided by Dont-code offering next versions of all plugins",
  "webSocketUrl": "ws://test.dont-code.net/demo/preview",
  "storeApiUrl": "https://test.dont-code.net/demo/data",
  "projectApiUrl": "https://test.dont-code.net/demo/project",
  "documentApiUrl": "https://test.dont-code.net/demo/documents",
  "plugins": [
    {
      "id": "Basic",
      "display-name": "Basic plugin for editing entities",
      "version": "1.0.0",
      "info": {
        "remote-entry":"https://run.dont-code.net/plugins/next/remoteEntry.mjs"
      },
      "config": {}
    },
    {
      "id": "Fields",
      "display-name": "Additional editors for entity properties",
      "version": "1.0.0",
      "info": {
        "remote-entry":"https://run.dont-code.net/plugins/next/remoteEntry.mjs"
      },
      "config": {}
    },
    {
      "id": "Rest",
      "display-name": "Plugins to support datasources from Rest API",
      "version": "1.0.0",
      "info": {
        "remote-entry":"https://run.dont-code.net/plugin-rest/next/remoteEntry.mjs"
      },
      "config": {}
    },
    {
      "id": "Report",
      "display-name": "Plugins to generate and display reports",
      "version": "1.0.0",
      "info": {
        "remote-entry":"https://run.dont-code.net/plugin-report/next/remoteEntry.mjs"
      },
      "config": {}
    },
    {
      "id": "Commerce",
      "display-name": "Plugins to get prices from shops",
      "version": "1.0.0",
      "info": {
        "remote-entry":"https://run.dont-code.net/plugin-commerce/next/remoteEntry.mjs"
      },
      "config": {}
    }
  ]
}
